builds:
-
  main: ./cli
  env:
    - CGO_ENABLED=0
  goos:
   - linux
   - darwin
   - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
archives:
  - id: archive
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  -
    github:
      owner: stelligent
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@stelligent.com
    folder: Formula
    homepage:  https://github.com/stelligent/config-lint
    description: Validate configuration files using rules specified in YAML
    test: |
      system "#{bin}/config-lint -version"
dockers:
  - 
    dockerfile: .dockerhub/Dockerfile
    image_templates:
    - "stelligent/config-lint:{{ .Tag }}"
    - "stelligent/config-lint:latest"
