builds:
-
  main: ./cli
  env:
    - CGO_ENABLED=0
  goos:
   - linux
   - windows
  goarch:
    - 386
    - amd64
archives:
  - id: archive
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  - 
    dockerfile: .dockerhub/Dockerfile
    image_templates:
    - "ffsclyh/config-lint:{{ .Tag }}"
    - "ffsclyh/config-lint:latest"
